# Site settings
title: Hey! Watch Out
email: lenpendulm#gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Some intresting notes here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pendulm.github.io" # the base hostname & protocol for your site
twitter_username: pendulm
github_username:  pendulm

# Build settings
markdown: kramdown
